### ISSUE TITLE
Firefox is receiving Settings via GPO, but nothing happens

### ISSUE THREAD

**Issue by nkmup** [cadeyrn/enterprise-policy-generator#102]
**Describe the bug**
Firefox 69 is receiving the settings via GPO, and shows them correctly in the local settings. Nothing updates or installs.

**To Reproduce**
1. Install Firefox 69 on Win10Pro - 1903
2. Settings via GPO as outlined by Mozilla
3. Receive them in about:policies

**Expected behavior**
I just want domain wide adblocker

**Screenshots**
![GPOSettings](https://user-images.githubusercontent.com/55095111/64537162-97267080-d31a-11e9-9b47-011d2f319d66.PNG)

**Version information:**
 - Firefox version: 69.0 64-bit
 - Enterprise Policy Generator version 4.4.0

**Comment by cadeyrn** [comment]
Closing because this has nothing to do with the Enterprise Policy Generator add-on. I can't provide Firefox support in this repository.
