### ISSUE TITLE
new policy: DisablePasswordReveal

### ISSUE THREAD

**Issue by cadeyrn** [cadeyrn/enterprise-policy-generator#108]
DisablePasswordReveal => Firefox 71+
https://bugzilla.mozilla.org/show_bug.cgi?id=1586913

**Comment by varshannagarajan** [comment]
Hi, I was wondering if I could work on this issue?

**Comment by cadeyrn** [comment]
Hi,

yes! :) I will post some instructions tomorrow so that you know what you have to do to add a policy.

Thank you for your interest to contribute to Enterprise Policy Generator!

**Comment by varshannagarajan** [comment]
That would be amazing. I was trying to figure out what exactly I needed to do. I looked through some of your older commits where you added other policies to see what was required. But if you have some more details or instructions they would definitely be appreciated.

And no problem it seems like an interesting project!

**Comment by cadeyrn** [comment]
Hi,

1. All policies are defined in the file src/js/core/policies.js
https://github.com/cadeyrn/enterprise-policy-generator/blob/master/src/js/core/policies.js

2. Please note that there are many different types of policies. Unfortunately the documention is not yet ready. So I'll explain a few things.

3. I suggest to copy the `DisablePrivateBrowsing` policy because it's exactly what we want: a description and a simple checkbox to disable a feature.

4. The order of policies in the policies.js files determines the order of the policies in the user interface. There are already some password related policies and we should add the new one below these policies. I suggest to insert the new policy after the `PasswordManagerEnabled` policy.

5. Now let's change our copied `DisablePrivateBrowsing` policy. First you have to replace `DisablePrivateBrowsing` with the correct policy name, in this case `DisablePasswordReveal`. The translation key should always be `policy_description_POLICYNAME`, in this case `policy_description_DisablePasswordReveal`. The property `first_available` contains the first information when the policy is available in Firefox. The new policy will be in Firefox 71, so please change the `mainstream` property to `'71.0'` (don't remove the quotes). The policy is not yet in Firefox ESR, so instead of `'68.0'` the value for `esr` should be `null` (without quotes!). Because the password related policies are in the security section we have to change the `ui_category` property from `'disable-features'` to `'security'`.

6. All other properties are okay and don't need to be changed.

7. Now we have to add the translation for `policy_description_DisablePasswordReveal`. You can find the translation files in src/_locales/. Please add the new translation to all translation files and use the English translation for all languages. If you are able to translate in one of the other languages you can already translate this language, otherwise I will ask the translators to translate the new string at the end of the development of this version of Enterprise Policy Generator. Please insert the new translation on the correct position - the translations are sorted alphabetically. The `message` of the new translation should be "Do not allow passwords to be revealed in saved logins". 

That's all! :)

**Comment by varshannagarajan** [comment]
Thank you for the instructions! They were very helpful! I submitted a pull request with the fix, let me know if anything needs to be changed. Or if you have any other policies you would like to add I would not mind helping at all.

**Comment by cadeyrn** [comment]
Great, thank you very much for your contribution!

> Or if you have any other policies you would like to add I would not mind helping at all

There will be more new policies in the next release of Enterprise Policy Generator which will be released next week: https://github.com/cadeyrn/enterprise-policy-generator/issues/107

These policies are of a different policy type. In the next weeks I will write a complete documention (that's #103), but the documentation will be completed _after_ the release of the next version of Enterprise Policy Generator, so I will explain later today how to add these policies. And I will also add the English descriptions for every of these policies.

If you're interested you're more than welcome to contribute more. :) But to be clear: #107 contains 16 new policies. You can pick one of these, all or every number between. You don't have to implement all policies if you want to help. ;-)

I will close this issue because the DisablePasswordReveal policy is implemented, and will add the explanations for the other policies in #107.
