### ISSUE TITLE
add DefaultPrivate property to SearchEngines policy

### ISSUE THREAD

**Issue by cadeyrn** [cadeyrn/enterprise-policy-generator#111]
add DefaultPrivate property to SearchEngines policy => Firefox 71+
https://bugzilla.mozilla.org/show_bug.cgi?id=1587804

**Comment by varshannagarajan** [comment]
Hi, If you would like me to work on this I can. I just have a couple questions though, I understand that the `mainstream` property would be 71.0, but would the `esr` be null since I don't see any mention of when it will be added there? Also for the `ui_category` I was thinking it would fall under privacy, is that correct?

**Comment by cadeyrn** [comment]
@varshannagarajan:

Yes, if the ESR version is still unknown or if the policy won't be supported in Firefox ESR then the `esr` property has to be set to `null`. But in this case we don't want to add a new policy. Instead a new property has to be added to an already existing policy, the `SearchEngines` policy.

The `SearchEngines` policy already has a `Default` property and the new `DefaultPrivate` property should be added below this property because it's exactly the same but for private instead for regular browser windows (a seperate search for private windows is a new feature of Firefox 71 and won't be included in Firefox ESR 68).

You can copy the `Default` property and use `policy_description_SearchEngines_DefaultPrivate` as key for the tranlation. The translation should be "Name of the default search engine for private windows if different than for regular windows (Firefox 71+)" - we have to add the Firefox version to the translation because the policy is supported since Firefox 60 and only this property is new in Firefox 71.
