### ISSUE TITLE
Beschreibungstexte von OfferToSaveLogins und OfferToSaveLoginsDefault sind schwer verständlich (Verbesserungsvorschlag)

### ISSUE THREAD

**Issue by musonius** [cadeyrn/enterprise-policy-generator#112]
Die beiden Optionen

- Firefox erlauben oder verbieten, sich gespeicherte Logins und Passwörter zu merken
- Standard-Einstellung, ob sich Firefox gespeicherte Logins und Passwörter merkt

sind meiner Meinung nach schwer verständlich: Wie können gespeicherte Passwörter nicht gemerkt werden? Gelten die dann nur bis zum Sitzungsende?

Tatsächlich handelt es sich dabei um die Richtlinien _OfferToSaveLogins_ und _OfferToSaveLoginsDefault_. Auf der Seite `about:policies#documentation` steht als Erklärung von _OfferToSaveLogins_:

> Frage zum Speichern von Zugangsdaten durch Firefox anzeigen. Die Werte true und false werden akzeptiert.

Ich schlage daher vor, die Texte umzuändern in z.B.

- Frage zum Speichern von Zugangsdaten durch Firefox anzeigen
- Standardeinstellung, ob die Frage zum Speichern von Zugangsdaten durch Firefox angezeigt werden soll

Ich verwende derzeit Firefox ESR 68.1.0 und Enterprise Policy Generator  5.0.0

**Comment by cadeyrn** [comment]
Danke für den Vorschlag. Ich werde das für das kommende Update berücksichtigen.

**Comment by musonius** [comment]
Ein Verschreiber: "Brower-Chronik merken" - es fehlt ein 's'.
