### ISSUE TITLE
import-function for policies.json

### ISSUE THREAD

**Issue by WileC** [cadeyrn/enterprise-policy-generator#124]
Hello,

i think, it would be nice to import an existing policies.json to work with it on another workstation.

**Comment by cadeyrn** [comment]
Hi,

thanks for the suggestion. The file policies.json is used by Firefox but it doesn't contain any information specific to the Enterprise Policy Generator. So with only the policies.json file the Enterprise Policy Generator doesn't know which fields of the user interface of Enterprise Policy Generator have to be selected and so on.

But: There is already an export/import feature. You can export a configuration file of the Enterprise Policy Generator. It exports a *.policy file which contains all the information the Enterprise Policy Generator needs. This *.policy file can be imported on other workstations with Enterprise Policy Generator.

**Comment by WileC** [comment]
how can i export a configuration file *.policy?
