### ISSUE TITLE
Free text fields for the "preferences"

### ISSUE THREAD

**Issue by WileC** [cadeyrn/enterprise-policy-generator#125]
Hello,

i would like to specify my own preferences like "network.dns.ipv4OnlyDomains". So i need an empty input field to fill it with the preferece and an empty input field for the value.

see https://github.com/mozilla/policy-templates/blob/master/README.md#preferences

**Comment by cadeyrn** [comment]
Hi,

thanks for you suggestion. Unfortunately You can't set arbitrary about:config options via the Enterprise Policy Engine, only the preferences implemented by Mozilla.

There will be an update next week or the week after the next week which will implement all the missing preferences of Firefox 70/71/ESR 68.2/ESR 68.3 in Enterprise Policy Generator:

https://github.com/cadeyrn/enterprise-policy-generator/issues/107
https://github.com/cadeyrn/enterprise-policy-generator/issues/122
