### ISSUE TITLE
require an update about the permissions

### ISSUE THREAD

**Issue by WagnerGMD** [cadeyrn/enterprise-policy-generator#136]
**Describe the bug :**
Apparently, the addon doesn't have the data about the latest permissions (**"Autoplay"** and the **"Virtual Reality"**).
No I don't recall when the both has been integrated inside the browser Firefox (but I assume it was a few months ago).

**Screenshots :**
![Firefox-v79-ExtractPage-about:preferences](https://nsa40.casimages.com/img/2020/06/27/200627031004672370.png)
You can also just open the page **"about:preferences#privacy" !**

**Version information :**
 - Firefox = 79 (Nightly which was published 24 June 2020)
 - Enterprise Policy Generator (aka EPG) = 5.1.0 (it was published 27 February 2020)

**Expected behavior :**
The next release must be update. Because the generator won't be able to create a complete file **"policies.json" !** 
Otherwise, you should give us the syntax to block each permissions.

**Comment by cadeyrn** [comment]
Autoplay:

```
{
  "policies": {
    "Permissions": {
      "Autoplay": {
        "Allow": ["https://example.org"],
        "Block": ["https://example.edu"],
        "Default": "allow-audio-video" | "block-audio" | "block-audio-video",
        "Locked": true | false
      }
    }
  }
}
```

A policy for Virtual Reality does not exist in Firefox.

There will be an update for Enterprise Policy Generator in July to support the Autoplay Permission and other new policies.

**Comment by cadeyrn** [comment]
There will be also a policy for VR in Firefox 80+ and Firefox ESR 78.2+. Both new policies, Autoplay and VirtualReality, will be supported in Enterprise Policy Generator 6.0, to be released this month.
