### ISSUE TITLE
Page not found

### ISSUE THREAD

**Issue by wistein** [cadeyrn/enterprise-policy-generator#2]
Unfortunately the add-on is currently not available on Mozilla's site.
The given link results in "Page not found".
A search on Firefox Add-ons page gives no result.

Using Firefox 60.0 ESR.

Regards,
wistein

**Comment by cadeyrn** [comment]
Hi,

it's because it's not yet released. I will release the add-on in the next days.

**Comment by cadeyrn** [comment]
Hi,

the add-on has been released a few moments ago!
https://addons.mozilla.org/en-US/firefox/addon/enterprise-policy-generator/

**Comment by wistein** [comment]
Thank you for the info,

Best regards,
wistein


-----Ursprüngliche Nachricht-----
Von: Sören Hentzschel [mailto:notifications@github.com] 
Gesendet: Sonntag, 20. Mai 2018 17:45
An: cadeyrn/enterprise-policy-generator
Cc: Wilhelm Stein; Author
Betreff: Re: [cadeyrn/enterprise-policy-generator] Page not found (#2)

Hi,

the add-on has been released a few moments ago!
https://addons.mozilla.org/en-US/firefox/addon/enterprise-policy-generator/
