### ISSUE TITLE
Where does Enterprise Policy Generator save policy files

### ISSUE THREAD

**Issue by NorbertVlm** [cadeyrn/enterprise-policy-generator#213]
I am using Firefox 102.12 ESR portable.  I created a policy (Generate Policies) and clicked 'Save Configuration'.   I then changed the policies.  Hit 'Generate Policies' again.  Then I clicked 'load configuration'.  The saved policy file was loaded and overwrote the new policies.  

I am unable to find where it is saving the Policies.json files. I created a Distribution folder, but it didn't save there.  :(  

Can your help?

thanks
Norbert

**Comment by cadeyrn** [comment]
"Save Configuration" saves the current configuration within the add-on's storage so that you can change it at a later point without doing everything from scratch again.

For using the policies in Firefox you have do use the "Download policies.json" button. You choose the destination yourself.
