### ISSUE TITLE
new policy: AppUpdateURL

### ISSUE THREAD

**Issue by cadeyrn** [cadeyrn/enterprise-policy-generator#29]

**Comment by cadeyrn** [comment]
@xerta555 

Hi!

there is one new string for translation. 

```
"policy_description_AppUpdateURL": {
  "message": "Different server URL for Firefox updates"
}
```

Thank you!

**Comment by xerta555** [comment]
> @xerta555
> Hi!
> there is one new string for translation.
> Thank you!

Done :) :+1:
