### ISSUE TITLE
'Read certificates from the Windows certificate store' error

### ISSUE THREAD

**Issue by StanGets** [cadeyrn/enterprise-policy-generator#46]
Hi,

Enterprise Policy Generator (EPC) 4.0 / Firefox 62.0 (x64)

EPC / Security / Read certificates from the Windows certificate store (Windows only)
handles Firefox's `security.enterprise_roots.enabled` _false_ by default

Setting _Read certificates from the Windows certificate store (Windows only)_ to _**don't read certificates from the Windows Certificate store**_ sets accordingly the policy template to

>  "policies": {"Certificates": {"ImportEnterpriseRoots": false}

But when restarting Firefox the value of `security.enterprise_roots.enabled` is hardcoded to _true_ when it should be hardcoded to _false_

Given the policy template _"policies": {"Certificates": {"ImportEnterpriseRoots": false}_ is correct, this seems more as a Firefox issue than a wrong configuration of EPC

**Comment by cadeyrn** [comment]
Hi,

after checking the checkbox a dropdown appears. There you can set this value either to true or to false.

**Comment by StanGets** [comment]
Hi,

> after checking the checkbox a dropdown appears. There you can set this value either to true or to false.

That is what I've done as explained above: I've chosen from the drop-down **don't read certificates from the Windows Certificate store** which created accordingly the template `"policies": {"Certificates": {"ImportEnterpriseRoots": false}` and that should lead to `security.enterprise_roots.enabled` **= _false_ and not _true_.**

**Comment by cadeyrn** [comment]
Hi,

I can confirm that Firefox sets security.enterprise_roots.enabled always to true with this policy enabeld, both with ImportEnterpriseRoots set to true and false. I will report it to Mozilla.

**Comment by StanGets** [comment]
@cadeyrn thanks. Obviously it's a Firefox issue.
Because I use Firefox's Autoconfig as well as, I've added to my Autoconfig's config.js:
```
// DISABLE USING THE WINDOWS CERTIFICATE STORE
lockPref("security.enterprise_roots.enabled", false);
```
_false_ is the default value anyway. I was aiming to enforce it via the Policy templates and until Mozilla fixes the issue I'll keep the Autoconfig setting.

**Comment by StanGets** [comment]
Mozilla hasn't provided any answer yet on https://bugzilla.mozilla.org/show_bug.cgi?id=1491664
Maybe companies don't really interest Mozilla? Whatever this policy template mistake is a heavy one in terms of possible implications. I'm really disappointed with Mozilla's silence on this issue.

**Comment by StanGets** [comment]
> if that were true then there would be no Enterprise Policy Engine at all, no AutoConfig and no one would be working on MSI installers

Certainly if companies weren't at all the concern of Mozilla; I was wondering if companies _really_ interested Mozilla, that is beyond rhetoric and extended to a seriously driven policy templates' management. Letting the error I reported, the error further on reported to bugzilla without a prompt answer from Mozilla explains my doubts.

**Comment by cadeyrn** [comment]
You can't expect prompt answers to every report. That's not how things work. I already report bugs since a few years. Sometimes you have to wait a bit. It doesn't mean that's not important for Mozilla.

But this discussion should not be held here.

**Comment by cadeyrn** [comment]
There was an answer in the ticket:

> I'm definitely planning to fix this in the code, but it was written to spec originally.
> 
> I've updated the documentation.

For Enterprise Policy Generator this means the following: The next update is scheduled for October 23, 2018. If there will be a code change in Firefox before this date no action is needed. If there won't be a code change in Firefox before this date I will change the option in Enterprise Policy Generator to reflect the reality and make sure that there will be no issues with saved configurations.

**Comment by StanGets** [comment]
@cadeyrn , I read that answer in the ticket. I understand the implication on _Enterprise Policy Generator_ of course and acknowledge your management of the problematic. Clear enough. Thanks.

**Comment by cadeyrn** [comment]
I added a note that the option not to read certificates from the Windows certificate store only works on Firefox 64 and higher (Mozilla fixed the issue in Firefox 64).
