### ISSUE TITLE
Saving configurations reverses the order of bookmarks

### ISSUE THREAD

**Issue by YayILikePie** [cadeyrn/enterprise-policy-generator#47]
After creating a customized policies.json, after saving a configuration, the bookmarks are stored in reverse order after loading the saved configuration.

**Comment by cadeyrn** [comment]
Thanks for using the Enterprise Policy Generator and reporting the issue. I was not able to reproduce the issue. Could you please attach two screenshots* so that I can try to do exactly the same?

*) The first screenshot should show the input fields of your bookmarks section on the left side and the generated policies.json on the right side before saving the configuration. The second screenshot should show the same but after loading the saved configuration.

Thank you!

**Comment by YayILikePie** [comment]
I split it into four screenshots instead, since I want to make sure you can see the full policies.
Let me know if you need any further information.
Thanks, Sören.

David Wan
Desktop and Application Support Specialist
Information Technology
UC Davis School of Veterinary Medicine
Office: (530) 752-8953
Mobile: (530) 979-1477

**Comment by cadeyrn** [comment]
Unfortunately there are no screenshots.

**Comment by cadeyrn** [comment]
Thank you. I will try to reproduce the issue on the weekend.

**Comment by cadeyrn** [comment]
Sorry for the delay. Could you please re-check if this still happens with Firefox ESR 60.3? I will also test this weekend (this times really because I want to release an update this weekend).

**Comment by YayILikePie** [comment]
Hi Sören,
I just tested again using Firefox 60.3.0 ESR, along with Enterprise Policy Generator 4.0.0, with the same result. Bookmarks end up in reverse order after saving configuration and reloading configuration.

David Wan
Desktop and Application Support Specialist
Information Technology
UC Davis School of Veterinary Medicine
Office: (530) 752-8953
Mobile: (530) 979-1477

**Comment by cadeyrn** [comment]
Thanks for checking! I will have a look.

**Comment by cadeyrn** [comment]
I found the cause.

Could you please test this version?
https://send.firefox.com/download/20c33a5f24/#coziklFluvnDvFo3lx9glA

It's not signed so you have to open about:debugging in your Firefox and load the new version via about:debugging.

Does this version fix the issue for you?

Thank you for your help.

**Comment by cadeyrn** [comment]
I found the cause. It's fixed in Enterprise Policy Generator 4.1. Let me know if you see more issues. Thank you!
