### ISSUE TITLE
policies.json not work

### ISSUE THREAD

**Issue by luremus007** [cadeyrn/enterprise-policy-generator#51]
policies not work in firefox, created with enterprise policy generator
![mozilla](https://user-images.githubusercontent.com/44022312/46728226-37db5e80-cc7a-11e8-92ad-2b6ea6f5092a.JPG)

**Comment by luremus007** [comment]
thx for the quickly answer.
The content is:
-----------
{
  "policies": {
    "DisableTelemetry": true,
    "DisplayBookmarksToolbar": false,
    "Extensions": {
      "Install": ["C:\\Program Files\\Mozilla Firefox\\distribution\\pornmalware_blocker-1.4-fx.xpi"]
    }
  }
}
---------

Nothing works, the policies will not applying.
The picture above contents all information.

**Comment by cadeyrn** [comment]
Both DisableTelemetry and DisplayBookmarksToolbar works for me. Please note that DisableTelemetry is a locked preference. With this policy applied it can't be changed by the user. But DisplayBookmarksToolbar is not a locked preference, it only sets the default value. The user can show or hide the toolbar at any time.

I can't test your Extensions policy because I don't use Windows.

You could install Firefox 63 Beta and open the page about:policies. There you can see if there are errors in your policies. This feature is not available in Firefox 62.

**Comment by luremus007** [comment]
i installed FF beta 63, about:policies = Error parsing JSON file.

if telemetry would work, i can only trust it.
bookmark false is only for test, i will enable it after a fresh installation.
extensions autoinstall would be nice.

i try now just one week also with GPO in a domain, this will not work too.
i give up

(for google chrome: it works without any troubles, GPO and preferences!)

**Comment by luremus007** [comment]
Habe FF beta 63 installiert, about:policies = Error parsing JSON file.

Ob Telemetrie wirklich funktionier kann ich nicht überprüfen, nur vertrauen.
Bookmark will ich (wenns funktioniert) einschalten nach installation.
Extensions automatisch installieren wäre nett.

Ob es der user ändern kann oder nicht ist sekundär

i installed FF beta 63, about:policies = Error parsing JSON file.

if telemetry would work, i can only trust it.
bookmark false is only for test, i will enable it after a fresh installation.
extensions autoinstall would be nice.

i try now just one week also with GPO in a domain, this will not work too.
i give up

(for google chrome: it works without any troubles, GPO and preferences!)



Von: Sören Hentzschel [mailto:notifications@github.com]
Gesendet: Mittwoch, 10. Oktober 2018 19:03
An: cadeyrn/enterprise-policy-generator <enterprise-policy-generator@noreply.github.com>
Cc: luremus007 <sh4u@outlook.com>; Author <author@noreply.github.com>
Betreff: Re: [cadeyrn/enterprise-policy-generator] policies.json not work (#51)


Both DisableTelemetry and DisplayBookmarksToolbar works for me. Please note that DisableTelemetry is a locked preference. With this policy applied it can't be changed by the user. But DisplayBookmarksToolbar is not a locked preference, it only sets the default value. The user can show or hide the toolbar at any time.

I can't test your Extensions policy because I don't use Windows.

You could install Firefox 63 Beta and open the page about:policies. There you can see if there are errors in your policies. This feature is not available in Firefox 62.

**Comment by cadeyrn** [comment]
> i installed FF beta 63, about:policies = Error parsing JSON file.

Then there is a syntax error in your JSON file. Please note that in your previous comment all the "\\" have to be "\\\\" in the extension install path. It's a GitHub bug that backslashes have to be escaped in comments. But in your screenshot it's correct. If I use the JSON content from your previous comment without repairing the path then I also get the message "Error parsing JSON file". If I escape the backslashes the only error I see is the install path because the path does not exist on my system. Both other policies are applied.

> if telemetry would work, i can only trust it.

You can check this. The checkbox in about:preferences is disabled and can't be changed. But this won't work until the syntax error is fixed. With syntax error in the JSON file no policies are applied.

> (for google chrome: it works without any troubles, GPO and preferences!)

I don't have any troubles with Firefox. ;)

**Comment by luremus007** [comment]
Now it works policies.json, definitiv it looks like it now:
[cid:image001.png@01D4615D.54280A30]

noteworthy is the number of backslashes! (I had double backslashes bevor)

About telemetriy:

I mean, you can not really control that, even though the policy works

-----------------------------------

i installed FF beta 63, about:policies = Error parsing JSON file.

Then there is a syntax error in your JSON file. Please note that in your previous comment all the "\" have to be "\\" in the extension install path. It's a GitHub bug that backslashes have to be escaped in comments. But in your screenshot it's correct. If I use the JSON content from your previous comment without repairing the path then I also get the message "Error parsing JSON file". If I escape the backslashes the only error I see is the install path because the path does not exist on my system. Both other policies are applied.

if telemetry would work, i can only trust it.

You can check this. The checkbox in about:preferences is disabled and can't be changed. But this won't work until the syntax error is fixed. With syntax error in the JSON file no policies are applied.

(for google chrome: it works without any troubles, GPO and preferences!)

I don't have any troubles with Firefox. ;)

**Comment by luremus007** [comment]
![mozilla2](https://user-images.githubusercontent.com/44022312/46801322-4432ea80-cd52-11e8-846c-4a57a615c22b.JPG)
![mozilla3](https://user-images.githubusercontent.com/44022312/46801323-4432ea80-cd52-11e8-9593-e4445efcb31e.JPG)

**Comment by cadeyrn** [comment]
That's weird. In my opinion double backslashes should be the correct way. :-/ But since I don't have Windows I can't check.

> I mean, you can not really control that, even though the policy works

You can trust that it works because Firefox is open source and there would be a really big shitstorm if the telemetry setting were a fake. ;-)

**Comment by luremus007** [comment]
kleine Anregung:
please add a button to browse and load the path and filename in this field.

finaly:
If the EPG should also work correctly under ff for windows (and macOS), you also have to test it under windows (and macOS), not only Linux
![mozilla5](https://user-images.githubusercontent.com/44022312/46807926-fe325280-cd62-11e8-8bf2-b8058d659848.JPG)

**Comment by cadeyrn** [comment]
I asked for clarification about the correct way to write pathes on Windows:
https://github.com/mozilla/policy-templates/issues/267

> If the EPG should also work correctly under ff for windows (and macOS), you also have to test it under windows (and macOS), not only Linux.

I only use macOS. Like most developers I don't have access to all operating systems and depend on feedback of the users.  ;-)

**Comment by luremus007** [comment]
thx

PS: i have, among other things, a notebook with tribpe-boot: windows and two different linux

**Comment by cadeyrn** [comment]
Mike Kaply said that two backslashes should be enough. Could you please test again and if you still needs for backslashes file a bug in Mozilla's bugtracking system?

https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox&component=Enterprise+Policies
