### ISSUE TITLE
configuration corrupt after completing the option "remove search engines"

### ISSUE THREAD

**Issue by beware-of-froggy** [cadeyrn/enterprise-policy-generator#63]
Whenever I fill the option "delete search engines", with values like ebay DuckDUCKGo Amazon.fr the configuration file gets corrupted during the backup and we can not load it anymore to modify. Does this also give an inconsistent policies.json file misinterpreted?

the problem appears when the list is equal or exceeds 3 sites 3 values / 3 lines

**Comment by cadeyrn** [comment]
Thank you for using the Enterprise Policy Generator and filing the issue report.

Could you please share a detailled list of steps to reproduce the problem? Please also show me your configuration, maybe as screenshot.

**Comment by beware-of-froggy** [comment]
Hello thanks for your answer.

I am in the last version

you will find in this zip file an export of the functional policy configuration file before I add an additional search engine in the option "remove search engines" ...and then not working after saving and trying to load configuration

you can import it and open it

[policy-export-1542284911935.zip](https://github.com/cadeyrn/enterprise-policy-generator/files/2585344/policy-export-1542284911935.zip)


I then add a third search engine deletion (Amazon.fr) in this configuration file
The backup of the configuration is going well but we can not then reload the configuration. It appears in the list but the button no longer loads.
 the list of configurations remains displayed on the screen.
I thought it was a simple mistake because of the number of deleted engines but if I leave a blank file by only changing this option there is no blocking. May be must also be a correlation with the number of options defined and the file length generated (a parentheses or brace or separator badly closed?)

**Comment by cadeyrn** [comment]
Thank you, I can confirm the problem. I will check this soon.

**Comment by beware-of-froggy** [comment]
Thank you for your reply



And thanks for your work developping this very useful tool


nb:
I thought I could inject the policies.json file into a  Firefox windows installer repackaged  as I usually do to have a package with basic initial lock options that I could later change GPO options to business use and changes to the information system. But apparently as soon as I modify only one of the options by GPO it completely deactivates the options of the file policies.json (instead of doing a fusion of the rules it is a pity and not practical of the blow I am obliged to deploy a package without any restriction to finally  do everything by GPO for user restrictions relying only on the good execution of GPO to lock the package which is initially open completely

**Comment by cadeyrn** [comment]
I found the cause and fixed the bug. The new version 4.1.1 contains the fix and has been released. Thank you again for reporting the issue.
