### ISSUE TITLE
Possibility to remove Bookmarks

### ISSUE THREAD

**Issue by Ph4te** [cadeyrn/enterprise-policy-generator#7]
If I'm adding a boomark folder and the profile already has one or more folders with this name, I'd like to have an option which would delete these folders and their bookmarks in it, prior to creating the new one.

**Comment by cadeyrn** [comment]
Hi,

Enterprise Policy Generator can't change the behaviour of the policies. The add-ons supports all what is supported by Firefox. If you wish a new policy or a new option for an existing policy you should suggest it to Mozilla:

https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox&component=Enterprise%20Policies
