### ISSUE TITLE
Import/export policies

### ISSUE THREAD

**Issue by TriMoon** [cadeyrn/enterprise-policy-generator#70]
**Describe the bug**
Several things wrong with this feature:
  - Exporting to file saves a file with garbled contents which look like base64 encoded ASCII
  - Importing:
    - The file browser opens with a `*.policy` filter, which should be `*.json` or `policies.json`
    - When you clear the filter and select a working `policies.json` file, it's settings are not imported at all because all settings in the UI stay blank.

**To Reproduce**
1. Open the "Enterprise Policy Generator" page
2. Check-mark any option, fe. first one
3. Click "Generate Policies", you will get this on screen:
```json
{
  "policies": {
    "BlockAboutAddons": true
  }
}
```
4. Click on "Download policies.json" and save the file.
5. The contents of the file is NOT JSON but  something like base64.
   - This only happend the first time it seems, because while writing this issue i tried the steps multiple times and it now miraculously saves proper JSON :confused: 
6. Press `F5` to refresh the page and clear all settings.
7. Click on "import configuration" to load a working `policies.json` file.
8. **No settings are shown from the imported file.**

**Expected behavior**
User expects to see the settings from the imported `policies.json` file to show in the UI

**Version information:**
 - Firefox version:
   **Mozilla/5.0 (X11; Linux x86_64; rv:67.0) Gecko/20100101 Firefox/67.0 ID:20190130215539**
 - Enterprise Policy Generator version:
   **4.3.0**

**Additional context**
See description

**Comment by cadeyrn** [comment]
Hi,

this works as intended. The export feature exports a configuration file for the Enterprise Policy Generator with the file format .policy. If it looks "like base64 encoded ASCII" then it works correctly. That's the file format that can be read by Enterprise Policy Generator. And the import feature expects a .policy file.

You can't import a policies.json file for a simple reason: The information in the policies.json file are used by Firefox, but the file policies.json does not contain any information about the fields of Enterprise Policy Generator. So with the content of policies.json the Enterprise Policy Generator can't know which fields in the user interface of Enterprise Policy Generator have to be filled with which values.

**Comment by TriMoon** [comment]
> Hi,
> 
> this works as intended. The export feature exports a configuration file for the Enterprise Policy Generator with the file format .policy. If it looks "like base64 encoded ASCII" then it works correctly. That's the file format that can be read by Enterprise Policy Generator. And the import feature expects a .policy file.
> 
> You can't import a policies.json file for a simple reason: The information in the policies.json file are used by Firefox, but the file policies.json does not contain any information about the fields of Enterprise Policy Generator. So with the content of policies.json the Enterprise Policy Generator can't know which fields in the user interface of Enterprise Policy Generator have to be filled with which values.

That's completely absurd, because the whole point of this addon is to generate a `policies.json` file !
This addon should use all fields it recognizes in the `policies.json`, use defaults for missing ones and skip those it doesn't. (maybe even give feedback about those not recognized)
NOT being able to read a file that it is intended to produce is a major design defect IMHO...

**Comment by cadeyrn** [comment]
> That's completely absurd, because the whole point of this addon is to generate a policies.json file

I wouldn't write it if it was "absurd". I am the developer of the add-on, I know how **my** add-on works.

> whole point of this addon is to generate a policies.json file

And the add-on does exactly that. To download the file policies.json and to export a Enterprise Policy Configurator are two entirely different things.

> This addon should use all fields it recognizes in the policies.json, use defaults for missing ones and skip those it doesn't.

That can't work and I've already explained why.

> NOT being able to read a file that it is intended to produce is a major design defect IMHO...

Nope. That's not possible at all.

> As mentioned in the OP step 5 comment, it actually saves JSON at moment and not the internal style you mentioned is what it expects...

Download: policies.json
Export: something.policy

**Comment by cadeyrn** [comment]
I will lock the issue because of your aggressive and offensive comment:

> That's completely absurd
