### ISSUE TITLE
AVG Detects EPG as a "Poorly Rated Browser Extension" and Encourages Deletion. w/ Nag.

### ISSUE THREAD

**Issue by DrakeJones** [cadeyrn/enterprise-policy-generator#72]
**Describe the bug**
I don't think it's a bug with EPG and AVG support is defiantly standing by the poor rating with no user option to rate the extension.

**To Reproduce**
1. Go to Firefox executable
2. Click on Firefox executable 
3. See error "Poorly Rated Browser Extension" 2 of 5 stars. Enterprise Policy Generator

**Expected behavior**
No false positive and no nag.

**Screenshots**
https://imgur.com/GJdi7mY

**Version information:**
 - Firefox version: [e.g. Firefox 64, Firefox ESR 60.4]
 - Enterprise Policy Generator version [e.g. 4.3.0]

**Additional context**
AVG Support is VERY unhelpful with false positives and end-user input/choice.  Maybe they will be more responsive to you.

**Comment by cadeyrn** [comment]
Hi,

thanks for the notice. I can try to ask them to stop this nonsense but I don't think they will do anything. People should really not use software from Avast / AVG beause that's really bad software - bad for security and always causing problems for Firefox users.

**Comment by DrakeJones** [comment]
Good luck.  I don't like AVG, but the AVG firewall has the most configurable and granular firewall control I have found. ZoneAlarm lacks flexibility.  Your recommendation for antivirus with a highly configurable firewall for windows 7?

**Comment by cadeyrn** [comment]
On Windows you don't need anything else than the Windows Defender.

See this article from a former Mozilla employee:
https://robert.ocallahan.org/2017/01/disable-your-antivirus-software-except.html

Google engineers say the same:
https://www.onmsft.com/news/google-chrome-engineer-says-windows-defender-the-only-well-behaved-av

**Comment by DrakeJones** [comment]
Interesting...  Thanks.

**Comment by cadeyrn** [comment]
AVG fixed the false detection.

**Comment by DrakeJones** [comment]
Congratulations!  If AVG had told me, I wouldn't have believed it...
