### ISSUE TITLE
proxy settings doesn't work

### ISSUE THREAD

**Issue by Blodo** [cadeyrn/enterprise-policy-generator#81]
I set the proxy settings via the Enterprise Policy Generator and save the file under ...\distribution
When I restart Firefox and check the settings, nothing changes.
If I add the value - "Locked": true, -, the proxy settings in Firefox will be applied and displayed. 
But I want to distribute the proxy settings via json file and have the possibility to change the proxy settings manually in Firefox.  

The proxy settings doesn't apply:
{
  "policies": {
    "Proxy": {
      "AutoConfigURL": "http://172.16.***.***:****/xxx.pac",
      "AutoLogin": true,
      "Mode": "autoConfig",
      "Passthrough": "localhost, 127.0.0.1,172.16.0.0/16",
      "SOCKSVersion": 4,
      "UseHTTPProxyForAllProtocols": true,
      "UseProxyForDNS": false
    }
  }
}

The proxy settings apply and are locked:
{
  "policies": {
    "Proxy": {
      "AutoConfigURL": "http://172.16.***.***:****/xxx.pac",
      "AutoLogin": true,
	  "Locked": true,
      "Mode": "autoConfig",
      "Passthrough": "localhost, 127.0.0.1,172.16.0.0/16",
      "SOCKSVersion": 4,
      "UseHTTPProxyForAllProtocols": true,
      "UseProxyForDNS": false
    }
  }
}

 - Firefox version: 66.0.3
 - Enterprise Policy Generator version 4.4.0

**Comment by cadeyrn** [comment]
Please report bugs in the policy engine to Mozilla:
https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox&component=Enterprise+Policies

The Enterprise Policy Generator only generates the JSON file. If something does not apply then it's a bug in Firefox.

Thank you.
