### ISSUE TITLE
Add a feature that prevents users from installing add-ons/themes/etc.

### ISSUE THREAD

**Issue by vF360** [cadeyrn/enterprise-policy-generator#82]
Even though about:addons is blocked I can still install extensions through mozilla.org. Adding the mozilla domain to the block list doesn't work either. No website blocker I downloaded is able to block it for some reason.

**Comment by cadeyrn** [comment]
Hi,

please report bugs in the Enterprise Policy Engine to Mozilla:
https://bugzilla.mozilla.org/home

The Enterprise Policy Generator only generates the policy file, but has nothing to do with the functionality of the policies.

Thank you.

**Comment by vF360** [comment]
> 
> 
> Hi,
> 
> please report bugs in the Enterprise Policy Engine to Mozilla:
> https://bugzilla.mozilla.org/home
> 
> The Enterprise Policy Generator only generates the policy file, but has nothing to do with the functionality of the policies.
> 
> Thank you.

There isn't a policy feature that prevents installing extensions/themes/etc so it's not a bug.

**Comment by cadeyrn** [comment]
The same applies for feature requests. You have to ask Mozilla. As I said: The Enterprise Policy Generator only generates the policy file. I can only implement options in the Enterprise Policy Generator for policies which exist in Firefox.
