### ISSUE TITLE
Re-enable DisableSafeMode policy

### ISSUE THREAD

**Issue by Wizard13** [cadeyrn/enterprise-policy-generator#94]
In v4.1.0 it states that : “removed the policy to disable the safe mode because it’s not supported via policies.json, only via GPO”
However, it still works with policies.json and I still see this policy in  https://github.com/mozilla/policy-templates/blob/master/README.md#disablesafemode

**Comment by cadeyrn** [comment]
This seems to be an error in the new documentation.

> the DisableSafeMode policy is a very special case in Firefox as it's not handled by the policy engine, because the safe mode code runs much earlier than that.
> 
> So what we did was to add Windows specific code that directly checks the registry for this policy. This means that it's only supported on GPO, and not on policies.json, but that's fine as that is documented.

https://bugzilla.mozilla.org/show_bug.cgi?id=1496869#c5

**Comment by cadeyrn** [comment]
I confirmed on Apple macOS 10.15 Beta 3 that the DisableSafeMode polices does not work via policies.json.

**Comment by Wizard13** [comment]
With policies.json, DisableSafeMode doesn't prevent you from using command line parameters to start in safe mode, but it disables "restart with add-ons disabled" menu item, which is still useful for me when deploying firefox to schools.

**Comment by cadeyrn** [comment]
True. I will re-add this policy in Enterprise Policy Generator 5.0 and make it clear that it only affects the menu item.

There is no release date for version 5.0 yet but it will be sometime in the next few weeks.

**Comment by cadeyrn** [comment]
@Wizard13: Enterprise Policy Generator 5.0 contains the fix and was released a few minutes ago.
