### ISSUE TITLE
Typo in 'Configure certificates' for Linux

### ISSUE THREAD

**Issue by jcpearson** [cadeyrn/enterprise-policy-generator#95]
**Describe the bug**
The 'Import certificates' help text for Linux should be:

`distribution/certificates`

and not:

`distribution/Certificates`

**Version information:**
 - Firefox version:  Firefox ESR 68.0
 - Enterprise Policy Generator version: 4.4.0

**Additional context**

Firefox source code sets directory to use 'certificates' for Linux [here](https://hg.mozilla.org/releases/mozilla-esr68/file/tip/browser/components/enterprisepolicies/Policies.jsm#l181)

**Comment by cadeyrn** [comment]
Thanks for reporting!

**Comment by cadeyrn** [comment]
@jcpearson: Enterprise Policy Generator 5.0 contains the fix and was released a few minutes ago.
