### ISSUE TITLE
Can't add 'data:image' URL for search engine IconURL

### ISSUE THREAD

**Issue by jcpearson** [cadeyrn/enterprise-policy-generator#96]
**Describe the bug**

The 'Icon URL' input box gives 'invalid URL' when entering an inline encoded image and doesn't add the IconURL to the output policies.json

The 'URL' I'm using is:

`data:image/png;base64,iVBORw0KGgo...RK5CYII=`

(string shortened for brevity)

Manually adding such an IconURL string to the generated policies.json works fine

**Version information:**
 - Firefox version:  Firefox ESR 68.0
 - Enterprise Policy Generator version 4.4.0

**Additional context**

Interestingly, the input text box for the 'URL for searches' will accept a 'data:image/...' URL without complaining ...

Looking at the policy generator code (js/core/policies.js), it has:

```
 {
   name : 'URLTemplate',
   label : browser.i18n.getMessage('policy_description_SearchEngines_Add_URL'),
   mandatory : true,
   type : 'string'
 },
 {
   name : 'IconURL',
   label : browser.i18n.getMessage('policy_description_SearchEngines_Add_IconURL'),
   mandatory : false,
   type : 'url'
 },
```
Maybe the 'type' for 'IconURL' should be 'string' ?

**Comment by cadeyrn** [comment]
> Maybe the 'type' for 'IconURL' should be 'string' ?

Sounds like a good plan. Will be changed in Enterprise Policy Generator 5.0. There is no release date for version 5.0 yet* but it will be sometime in the next few weeks.

*) The current due date of the 5.0 milestone on GitHub does not reflect the current plannings. It will be released as soon as it's done and the due date of the 5.0 milestone can be understand as "not later than".

**Comment by cadeyrn** [comment]
@jcpearson: Enterprise Policy Generator 5.0 contains the fix and was released a few minutes ago.
