### ISSUE TITLE
Missing file:/// addons

### ISSUE THREAD

**Issue by Ph4te** [cadeyrn/enterprise-policy-generator#97]
Hi, 

I'm not sure if this belongs here. I'm testing FF ESR 68 right now and cannot import local xpi-Files.
The FF-Browser-Console tells me, that xpi-Files cannot be imported because of an error (0x804b0012 (NS_ERROR_UNKNOWN_PROTOCOL)).

If I specify the protocol by adding "file:///" before the File-Path everything works.

The Policy generator just creates the Path of the local xpi-File, but should instead also add the file-protocol.

**Comment by cadeyrn** [comment]
> The Policy generator just creates the Path of the local xpi-File, but should instead also add the file-protocol.

The Enterprise Policy Generator uses exactly what you entered in the text field. How should the extension know it has to add the file:// protocol and not https:// or http://?

**Comment by Ph4te** [comment]
In version 60.X ESR the file path without adding the protocol was enough. If I have to add it myself, an additional box would be helpful, advising that you have to add this prefix.

An idea would be to screen if the pathname begins with a Letter followed by a colon. Which is the usual Windows syntax for Pathnames.

**Comment by cadeyrn** [comment]
It's a bug in Firefox 68.0 that local file pathes no longer work without file:// protocol. Will be fixed in Firefox 68.1.
